#!/bin/sh

## Signal the Salt Master after getting a certificate.
sudo salt-call event.send certbot/$(basename ${RENEWED_LINEAGE})/deploy \
     "{\"domains\": $(echo -n "${RENEWED_DOMAINS}" | jq -Rsc '. / " " - [""]')}"
