#!/bin/sh

## Signal the Salt Master after getting a certificate.
sudo salt-call event.send certbot/deploy/$(basename ${RENEWED_LINEAGE}) \
     "{\"domains\": $(echo -n "${RENEWED_DOMAINS}" | jq -Rsc '. / " " - [""]')}"
